name: music_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_share: ^2.0.0
  url_launcher: ^6.1.9
  http: any
  dio: ^5.0.0
  avatar_glow: ^2.0.2
  acr_cloud_sdk: ^2.0.1
  cupertino_icons: ^1.0.5
  file_picker: ^5.2.5
  cloud_firestore: ^4.3.2
  firebase_storage: ^11.0.11
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  google_fonts: ^4.0.3
  font_awesome_flutter: any
  image_picker: ^0.8.6+1
  provider: ^6.0.5
  uuid: ^3.0.7
  just_audio: ^0.9.31
  audio_video_progress_bar: ^1.0.0
  cached_network_image: any
  another_flushbar: ^1.12.29
  youtube_player_flutter: ^8.1.2
  oktoast: ^3.3.1
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
